/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.avernakis.message.bus;

import org.junit.jupiter.api.*;

class MessageBusTest {
  class TestMessage extends Message {

  }
  private MessageBus messageBus;

  @BeforeAll
  static void setup() {}

  @BeforeEach
  void init() {
    messageBus = new MessageBus();
  }

  @Test
  @DisplayName("Empty queue is handled with timeout.")

  @Test
  @DisplayName("Empty queue is handled with blocking.")

  @Test
  @DisplayName("New message type can be registered.")

  @Test
  @DisplayName("Attempting to register the same type twice results in error.")

  @Test
  @DisplayName("Pushing a message of registered type onto the bus.")

  @Test
  @DisplayName("Pulling a message of registered type from bus.")

  @Test
  @DisplayName("Subscribing for events of a registered type.")

  @Test
  @DisplayName("Subscribing for events of a type not yet registered results in error.")

  @Test
  @DisplayName("Message bus executes callback when event ")

  @AfterAll
  static void teardown() {}

  @AfterEach
  void destroy() {}

}
