/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.message.bus;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;


class MessageBusTest {
    @Test 
    @DisplayName("This is testing getMessage()")
    void returnsAMessage() {
    }
}
